name: Create packages
on:
  schedule:
    - cron: "0 0 * * *" # run at the start of every day
  workflow_dispatch:

jobs:
  create-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v3

      - name: Repacking ubuntu packages
        run: sudo ./create-packages.sh

      - name: Generating release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::$(date +"%Y.%m.%d_%H-%M")"

      - name: Creating new release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          name: Automated arch package creation - ${{ steps.tag.outputs.release_tag }}
          body: |
            These are repacked ubuntu deb packages to be used in arch. [Explanation](https://github.com/eupnea-linux/arch-packages#explanation)
          files: |
            ./vboot-cgpt-utils.pkg.tar.zst